# Generated by Django 6.0.1 on 2026-01-10 13:29

import recipe_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=recipe_app.models.recipe_preview_directory_path, verbose_name='Изображение рецепта'),
        ),
    ]
