# Generated by Django 6.0.1 on 2026-01-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='recipe_app.category', verbose_name='Категория'),
        ),
    ]
