# Generated by Django 6.0.1 on 2026-01-10 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='recipe_app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_recipe', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
