# Generated by Django 6.0.1 on 2026-01-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='step',
            field=models.TextField(blank=True, verbose_name='Шаги приготовления'),
        ),
    ]
