# Generated by Django 6.0.1 on 2026-01-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0007_remove_recipe_category_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, null=True, verbose_name='Список ингредиентов'),
        ),
    ]
